# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fcf31de0fff84eb34d1857d02deac2965ecb2690e6a26c8c5e5812b24259f06c6c7598d6e4da55bc58a6740b35284cb7a1661bfba1cc7f8207fc8153f266643f

test:
  secret_key_base: d9fe26f7bb26f8c82a86730f54180528d10125dfedc8ae358509a62478f6a8fa96e29a784bae61ac569f58d5dea0d00e70cbdf49c5ce4690d98a4576ca7d6d6b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
